# Generated by Django 6.0.6 on 2026-07-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Product',
        ),
    ]
